In [1]:
import numpy as np
my_arr = np.arange(1000_000)
my_list = list(range(1000_000))
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 29.9 ms


In [2]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 1.08 s


In [3]:
data = np.random.randn(2, 3)
data

array([[ 0.64791094, -0.2551    , -2.01762846],
       [ 0.29944242,  1.2385739 , -0.24534737]])

In [4]:
%time data * 10

Wall time: 0 ns


array([[  6.47910937,  -2.55099997, -20.17628458],
       [  2.99442424,  12.38573897,  -2.45347368]])

In [5]:
data.shape
data.dtype

dtype('float64')

In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2
arr2.dtype

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

dtype('int32')

In [9]:
np.zeros((3, 6), dtype='int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [10]:
type(np.arange(15))

numpy.ndarray

In [11]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('int32')

dtype('float64')

In [12]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype="f8")
numeric_strings
# numeric_strings.astype(np.string_)
# numeric_strings.astype(np.float32)
# numeric_strings.astype(np.float16)

array([ 1.25, -9.6 , 42.  ])

In [13]:
arr = np.arange(10, dtype="f8")
arr
arr[5:8] = 12
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([ 0.,  1.,  2.,  3.,  4., 12., 12., 12.,  8.,  9.])

In [14]:
arr_slice = arr[5:8]
arr_slice[1] = 1.23456789
arr_slice
arr

array([12.        ,  1.23456789, 12.        ])

array([ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
       12.        ,  1.23456789, 12.        ,  8.        ,  9.        ])

In [15]:
arr1 = arr[5:8].copy()
arr1[1] = 666
arr1
arr
# arr2 = copy.deepcopy(arr)
# arr2

array([ 12., 666.,  12.])

array([ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
       12.        ,  1.23456789, 12.        ,  8.        ,  9.        ])

In [16]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
])
arr3d
arr3d[0]
arr3d.ndim
arr3d.shape

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

array([[1, 2, 3],
       [4, 5, 6]])

3

(3, 2, 3)

In [17]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
old_values

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr3d[0] = old_values
arr3d[0, 0]

array([1, 2, 3])

In [19]:
arr

array([ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
       12.        ,  1.23456789, 12.        ,  8.        ,  9.        ])

In [20]:
arr[1:6]

array([ 1.,  2.,  3.,  4., 12.])

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d
arr2d[:2]
arr2d[:2, 1:].shape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6]])

(2, 2)

In [22]:
arr2d[2, :2].shape
arr2d[:, :1]

(2,)

array([[1],
       [4],
       [7]])

In [23]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

array([[-0.07839586, -0.02064128,  2.37866994, -0.30150756],
       [ 0.3625299 ,  0.42935073,  1.21389492, -0.79378892],
       [-0.74844245, -0.27554848,  0.14210249, -1.22894314],
       [-1.44334083, -1.57544753,  0.53413024,  0.89830698],
       [ 0.02119723, -0.49442207, -1.42366585, -0.16479583],
       [ 1.27562163,  1.04699737, -0.42965624, -0.2631286 ],
       [ 0.09981013, -0.92220707,  1.45633719,  0.1255129 ]])

In [24]:
names == "Bob"
data[names == "Bob"]

array([ True, False, False,  True, False, False, False])

array([[-0.07839586, -0.02064128,  2.37866994, -0.30150756],
       [-1.44334083, -1.57544753,  0.53413024,  0.89830698]])

In [25]:
data[names == 'bob'.title(), :2]

array([[-0.07839586, -0.02064128],
       [-1.44334083, -1.57544753]])

In [26]:
import numpy as np
# 字节顺序标注
dt = np.dtype('<i2')
print(dt)

int16


In [27]:
import numpy as np
dt = np.dtype([('age',np.int8)]) 
dt
type(dt)

dtype([('age', 'i1')])

numpy.dtype[void]

In [28]:
mask = (names == "Bob")|(names == "Will")
mask
data[mask] = 6
data[mask]
data

array([ True, False,  True,  True,  True, False, False])

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

array([[ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 0.3625299 ,  0.42935073,  1.21389492, -0.79378892],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 1.27562163,  1.04699737, -0.42965624, -0.2631286 ],
       [ 0.09981013, -0.92220707,  1.45633719,  0.1255129 ]])

In [29]:
arr = np.arange(25).reshape(5,5)
bool_ = [True,False,True,False,False]
arr1 = arr[bool_]
arr1[1] = 2
arr1
arr

array([[0, 1, 2, 3, 4],
       [2, 2, 2, 2, 2]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [31]:
arr[[4,2]]

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.]])

In [32]:
arr = np.arange(32).reshape((8,4), order="F")
arr

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [33]:
arr = np.arange(24)
arr.reshape((4, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
a = np.arange(6).reshape(2,3)
a.ravel()[...] = 1
a

array([[1, 1, 1],
       [1, 1, 1]])

In [36]:
>>> from numpy import arange
>>> a = arange(16).reshape(2,2,2,2)
a
a.shape
a.ndim
a[..., 0].flatten()

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

(2, 2, 2, 2)

4

array([ 0,  2,  4,  6,  8, 10, 12, 14])